### ISSUE TITLE
borealis_convert increased complexity error triggered erroneously (I think)

### ISSUE THREAD

**Issue by alexchartier** [SuperDARN/pyDARNio#27]
# BUG 

When trying to convert Borealis HDF5 rawacf.hdf5.site files, I get the following error:

 The file cannot be converted to SDARN DMap rawacf due to the following error: Increased complexity: Borealis rawacf file record 1633013160047 blanked_samples [  0  72  96 160 176 208 216] does not equate to pulses array converted to sample number [ 0  9 12 20 22 26 27] * 8

On inspection of those arrays, they should be the same (i.e. each number in the first list is 8x the number in the second list). Therefore, the error message is incorrect. 

On further inspection, the cause of the error message is around line 424 of borealis_convert.py:
...
                sample_spacing = int(record['tau_spacing'] /
                                     record['tx_pulse_len'])
                normal_blanked_1 = record['pulses'] * sample_spacing
                normal_blanked_2 = normal_blanked_1 + 1 
                blanked = np.concatenate((normal_blanked_1, normal_blanked_2))
                blanked = np.sort(blanked)

                if not np.array_equal(record['blanked_samples'], blanked):
...

I don't understand why "normal_blanked_2" exists, or why it is concatenated into "blanked"
If we just did blanked = normal_blanked_1 instead, then it seems everything would work fine. 

## Priority
- [ ] Major - misrepresentation of data, failure in a common situation 
Fails each time we try to convert the rawacf.hdf5.site 

## Example of the bug 

from pydarnio import BorealisConvert
filename= '20210930.1446.00.wal.0.rawacf.hdf5.site'
borealis_filetype = 'rawacf'
dmap_filename = '/borealis_nfs/borealis_data/daily/20210930.1446.00.wal.a.rawacf.site'
slice_id = 0
borealis_converter = BorealisConvert(filename, borealis_filetype,
                       dmap_filename, slice_id, borealis_file_structure='site')

pydarnio.exceptions.borealis_exceptions.BorealisConvert2RawacfError: The file cannot be converted to SDARN DMap rawacf due to the following error: Increased complexity: Borealis rawacf file record 1633013160047 blanked_samples [  0  72  96 160 176 208 216] does not equate to pulses array converted to sample number [ 0  9 12 20 22 26 27] * 8

### Attempts

*What have you tried already to fix it?*

Tried commenting out the normal_blanked_2 stuff, got a different error: 
pydarnio.exceptions.borealis_exceptions.BorealisConvert2RawacfError: The file cannot be converted to SDARN DMap rawacf due to the following error: 'agc_status_word'

*What have you tried to get around it?*

### Data Location

to be uploaded here

*Please provide other pertinent details about this feature:*
Ubuntu linux

**Comment by alexchartier** [comment]
git won't let me upload the file

**Comment by alexchartier** [comment]
I have uploaded a file that won't convert here: https://drive.google.com/file/d/1vPKuJlbmK_E8it-rG67K3o1EMLtyohB5/view?usp=sharing

**Comment by mts299** [comment]
Actually, this issue came up with RKN Borealis update. Sorry for the delay our Engineers were away with getting Borealis on working on Rankin and Clyde. @RemingtonRohel @Lozzy-Bear  Can you comment on knowledge on this issue? 

I think we determined this might actually be a Borealis bug than a pyDARNio.

**Comment by alexchartier** [comment]
Thanks. What's the best way to set up automated testing of these conversion routines? Should we upload a set of "approved" files to convert on installation? If so, would they go in github or somewhere like Zenodo and get downloaded?

**Comment by alexchartier** [comment]
OK, I think we need two things going forward: 
#1 Conversion test routines in pydarnio so we can tell if the problem is bad files or bad pydarnio code
#2 Post a bug report when you find a problem

I also thought of going back to an older pydarn, but it seems the conversion code itself was always in pydarnio (it just stopped being imported by pydarn). So I'm not sure that would really fix it. But maybe I didn't follow the commit history closely enough

**Comment by RemingtonRohel** [comment]
@alexchartier I have found a couple borealis files of different versions that I have been testing with, I will send attach them here for you to download. 

From my testing, it looks like this is a pyDARNio bug, not borealis. I've made a branch with changes (https://github.com/SuperDARN/pyDARNio/tree/rawacf_dmap_conversion) that should fix the problem for borealis v0.5 files. 

I get the same error as you did about the agc_status_word, which I think is a separate issue. It looks to me like pyDARNio was updated for Borealis v0.6 which has agc_status_word and lp_status_word signals, but the lack of those signals in v0.5 files was somehow missed. From my testing it looks like that's the only other problem, and fixing that should allow your files to convert without issue.

**Comment by RemingtonRohel** [comment]
Here are two files, one v0.5 and one v0.6, which I used for testing along with yours:

https://drive.google.com/drive/folders/1j37Ez6JY_IlNAYXx2kG6IGR3aWzhMNMi?usp=sharing

**Comment by RemingtonRohel** [comment]
@alexchartier 

I've added two more files from 20211006 to the google drive link above, that I just tested. One is an hdf5 site file, and the other its dmap equivalent. I started with the hdf5 file, then converted it using pyDARN v1.1.0 since that's what we're using at site for all of our conversions, so I know if it converts with that then it has to be fine. It's good enough for what we upload, at any rate. I then converted it with pyDARNio on the branch I created, and then compared the two files, which were basically identical. The only difference was the 'combf' field in each record, because I gave two different paths to the hdf5 file when I converted two different ways.

With regards to "full conversion", BorealisConvert converts record-by-record, so I think that your conversion was probably just fine, even with a small data file. If it converts one record correctly, it should do the same for all records (ideally).

As for code that I used, I essentially used the exact same code as you just posted to generate my files. It was functionally identical. To generate the files with pyDARN v1.1.0, it was exactly the same thing but pydarn.BorealisConvert instead of pydarnio.BorealisConvert.

To compare DMap files, I used the following code:

```python
import numpy as np
import pydarnio

files = ['/home/remington/sample_data/dmap_generated/pydarnio.dmap',
         '/home/remington/sample_data/dmap_generated/20211006.2132.00.sas.a.rawacf.dmap']

SDarn_read_1 = pydarnio.SDarnRead(files[0])
SDarn_read_2 = pydarnio.SDarnRead(files[1])
rawacf_data_1 = SDarn_read_1.read_rawacf()
rawacf_data_2 = SDarn_read_2.read_rawacf()

for i in range(len(rawacf_data_1)):
    record_1 = rawacf_data_1[i]
    record_2 = rawacf_data_2[i]

    for key in record_1.keys():
        val_1 = record_1[key]
        val_2 = record_2[key]

        if not np.array_equal(val_1, val_2):
            # if key == 'combf':
            #     continue
            print("Different data:"
                  "\ti = {}\n"
                  "\t\tkey = {}\n"
                  "\t\t\tval_1 = {}\n"
                  "\t\t\tval_2 = {}"
                  "".format(i, key, val_1, val_2))
```

P.S. You can install a package from a branch with pip using `pip install git+git://github.com/SuperDARN/pydarnio.git@rawacf_dmap_conversion`. Do this within borealisrt_env and your realtime conversion should work.

**Comment by alexchartier** [comment]
For some reason that's not working for me - I get "Successfully built pydarnio" but then I can't import it from within python3 in borealisrt_env. Is there some other way of installing pydarnio such that the realtime code can use it?

**Comment by alexchartier** [comment]
@RemingtonRohel Thanks I think it is working now so I will close the issue. I recommend your fix be merged into the main pydarnio, along with a test routine based on those example files you uploaded and those code snippets. I can help implement that testing code, but I'm not sure where the examples files should be kept. 
Note: I was not able to install the package from a branch as you suggested. I had to change the following line in borealisrt_env/pyvenv.cfg :  include-system-site-packages = true
